name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.2
    - name: Restore dependencies
      run: dotnet restore
    #
    # Someday I will figure this out, but not today.
    # - name: check vars
    #  run: echo "$env:GITHUB_WORKSPACE"
    # - name: App Settings Variable Substitution
    #  uses: microsoft/variable-substitution@v1
    #  with:
    #    files: '$env:GITHUB_WORKSPACE\src\PowerUp.Tests\appsettings.json'
    #  env:
    #    DotNetCoreDirPathNet6: 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App\'
    #    DotNetCoreDirPathDefault: 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App\'
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
